### ISSUE TITLE
-norender flag necessary from wm_apply_ORG_atlas_to_subject.sh

### ISSUE THREAD

**Issue by tashrifbillah** [SlicerDMRI/whitematteranalysis#105]
### Description

Expose `wm_cluster_from_atlas.py`:`-norender` flag at `wm_apply_ORG_atlas_to_subject.sh`:

Since the flag [is not passed from the latter](https://github.com/SlicerDMRI/whitematteranalysis/blob/master/bin/wm_apply_ORG_atlas_to_subject.sh#L239), rendering is enabled, which crashes when run in headless mode e.g. without X forwarding or through bsub:

```vim
2020-12-23 16:25:06.664 (  73.611s) [        461F4380]vtkXOpenGLRenderWindow.:449    ERR| vtkXOpenGLRenderWindow (0x559532338920): bad X server connection. DISPLAY=
/PHShome/tb571/.lsbatch/1608758626.275372.shell: line 12: 25720 Aborted                 (core dumped) wm_cluster_from_atlas.py -j 16 TractRegistration/example-UKF-data/output_tractography/example-UKF-data_reg.vtk ../../../ORG-Atlases-1.2/ORG-800FC-100HCP FiberClustering/InitialClusters
```

This is the issue Fan noticed with `bsub` where the `wm_apply_ORG_atlas_to_subject.sh` job never completed, although most outputs (I suppose) were generated.

Let me know what you think about the above. If agreeable, I can devise an idea about hooking up `-x 1` flag with `-norender`.

### Way to reproduce

```vim
ssh eristwo
cd fan_s_home_dir # not writing here
source py3-wma/bin/activate
cd TESTING/WMA_eris2/example-UKF-data
wm_cluster_from_atlas.py -j 16 TractRegistration/example-UKF-data/output_tractography/example-UKF-data_reg.vtk ../../../ORG-Atlases-1.2/ORG-800FC-100HCP FiberClustering/InitialClusters
```

### Additional info

The below trick doesn't work. I suppose this was also the case for `wm_quality_control_tractography.py`:

> xvfb-run wm_cluster_from_atlas.py ...

**Comment by tashrifbillah** [comment]
In fact, do the above correction and run the `bsub` command you have in `instructions.txt` (in your home directory). It should no longer hang forever.

**Comment by zhangfanmark** [comment]
Thanks. I have changed "-norender" as default in ``wm_cluster_from_atlas.py``. 

https://github.com/SlicerDMRI/whitematteranalysis/blob/d26902d183e6226e6a56b064380cdd52114c3bbf/bin/wm_apply_ORG_atlas_to_subject.sh#L240

**Comment by tashrifbillah** [comment]
Thank you. Tested and confirmed!
