### ISSUE TITLE
Python 3.6 compatibility: fix apostrophe in author name

### ISSUE THREAD

**Issue by tashrifbillah** [SlicerDMRI/whitematteranalysis#106]
### Description
I have discovered a trifling reason that is preventing Python 3.6 installation of this software. In README.md, @ljod 's last name in the second paper has a special character instead of an apostrophe. I guess this happened because the paper name was copied from HTML format:

![image](https://user-images.githubusercontent.com/35086881/103118732-366d9500-463e-11eb-9b45-8693ff48a1de.png)

`setup.py` has [a step](https://github.com/SlicerDMRI/whitematteranalysis/blob/master/setup.py#L89) where README.md is read and decoded:

> long_description=open('README.md').read()

Python 3.6 is not able to decode that character which is why Python 3.6 based installation was failing so far:

```vim
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-req-build-vssux999/setup.py", line 89, in <module>
    long_description=open('README.md').read(),
  File "/home/pnlbwh/miniconda3/envs/wma36/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1578: ordinal not in range(128)
```
More specifically, the anomalous apostrophe is encoded as `\xe2\x80\x99` which I have discovered through `open('README.md', 'rb').read()`.

### Correction
While I understand that the recommended Python is 3.7, a simple fix is on our way from making this software Python 3.6 friendly. I have replaced that anomalous character and submitted a PR.

### Conclusion
It was fun and intriguing to solve this issue 🔑

**Comment by ljod** [comment]
Thanks!!!!

**Comment by zhangfanmark** [comment]
Thank you. Merged the pull request.
