### ISSUE TITLE
Subject space problem

### ISSUE THREAD

**Issue by Ferru21** [SlicerDMRI/whitematteranalysis#108]
Hi everybody,
I run de pipeline to perform the whole-brain tractography parcellation using the WMA and the anatomically ORG white matter atlas.
This includes the “wm_harden_transform.py” to transforms the fiber clusters in the atlas space back to the DWI subject space (Ussing “-i” in the command).

Finally I get the anatomical fibers, but they are not in the subject or the atlas space.
I use the Slicer 4.11v and I can choose the coordinate system before loading the model (RAS or LPS) but neither of the two works (see picture for the T_CST_left tract)

Any suggestions?
Thanks a lot

![unnamed-2](https://user-images.githubusercontent.com/85373489/120869313-8e54e400-c56c-11eb-8644-73e7967bd69a.jpg)

**Comment by Ferru21** [comment]
Thanks for your answer Fan
Yes, I tried with the 4.10 version but it has not worked either.

**Comment by Garand0o0** [comment]
Hi,
Is this problem solved? I ran into the same problem.

Thanks

**Comment by Garand0o0** [comment]
I tried the 4.10.0 version. There is a  new error.
![erorr](https://user-images.githubusercontent.com/38201671/124856708-9aa1e600-dfdd-11eb-90ef-56df8a0e0581.png)

Then I check the log file.But it is empty.
![log](https://user-images.githubusercontent.com/38201671/124857024-2287f000-dfde-11eb-8d21-6a00a24a94b3.png)

I didn't have this bug when I was using version 4.13, but there were subject space problem.

> Hi everybody,
> I run de pipeline to perform the whole-brain tractography parcellation using the WMA and the anatomically ORG white matter atlas.
> This includes the “wm_harden_transform.py” to transforms the fiber clusters in the atlas space back to the DWI subject space (Ussing “-i” in the command).
> 
> Finally I get the anatomical fibers, but they are not in the subject or the atlas space.
> I use the Slicer 4.11v and I can choose the coordinate system before loading the model (RAS or LPS) but neither of the two works (see picture for the T_CST_left tract)
> 
> Any suggestions?
> Thanks a lot
> 
> ![unnamed-2](https://user-images.githubusercontent.com/85373489/120869313-8e54e400-c56c-11eb-8644-73e7967bd69a.jpg)


9/5000

Does anybody know how to solve this？
Thanks

**Comment by zhangfanmark** [comment]
Hi, can you try to move the data to different folder so that only English characters are included in the path. Could be because of the Chinese characters in the file path. 

Fan

**Comment by zhangfanmark** [comment]
Hi can you share what the errors are with 4.10?

Fan

> Thanks for your answer Fan
> 
> Yes, I tried with the 4.10 version but it has not worked either.

**Comment by Garand0o0** [comment]
> Hi, can you try to move the data to different folder so that only English characters are included in the path. Could be because of the Chinese characters in the file path.
> 
> Fan

Thank you, it worked.
