### ISSUE TITLE
Issue During Separation by Hemisphere

### ISSUE THREAD

**Issue by kvandeloo-97** [SlicerDMRI/whitematteranalysis#115]
During step 6) 'Run hemisphere-based cluster separation using “wm_separate_clusters_by_hemisphere.py' I get the following error: 

- Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']

It will proceed to put all clusters into each sub-folder (all 3 will have 800 files). Please advise.

**Comment by zhangfanmark** [comment]
can you please post the full log please?

**Comment by kvandeloo-97** [comment]
Hi there, thank you for your fast response. I ran this example just on the command line, but also got the same error when running as a bash script. 

### Input command: 

wm_separate_clusters_by_hemisphere.py /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data ./SeparatedClusters/

### Output message before I initiated exit: 
(pnlpipe3) [klv16@grx06 TransformedClusters]$ wm_separate_clusters_by_hemisphere.py /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data ./SeparatedClusters/
Importing whitematteranalysis package.
<wm_separate_clusters_by_hemisphere.py> Output directory ./SeparatedClusters/ does not exist, creating it.
<wm_separate_clusters_by_hemisphere.py> Starting computation.

-----input directory -----
 /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data
-----output directory -----
 ./SeparatedClusters/
--------------------------

<wm_separate_clusters_by_hemisphere.py> Input number of vtk/vtp files:  800
<wm_separate_clusters_by_hemisphere.py> Separating input file: /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data/cluster_00001.vtp
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
<wm_separate_clusters_by_hemisphere.py> Separating input file: /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data/cluster_00002.vtp
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
<wm_separate_clusters_by_hemisphere.py> Separating input file: /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data/cluster_00003.vtp
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
<wm_separate_clusters_by_hemisphere.py> Separating input file: /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data/cluster_00004.vtp
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']

<wm_separate_clusters_by_hemisphere.py> Separating input file: /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data/cluster_00005.vtp
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
<wm_separate_clusters_by_hemisphere.py> Separating input file: /data/pnl/home/klv16/nov_ImagingSI/ATT01/ses-01/dwi/tractography/Clustering/TransformedClusters/sub-TRD03-UKF-data/cluster_00006.vtp
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
Data has unexpected tensor name(s). Unable to set active for visualization: ['tensor2']
^CTraceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/bin/wm_separate_clusters_by_hemisphere.py", line 188, in <module>
    main()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/bin/wm_separate_clusters_by_hemisphere.py", line 174, in main
    pd_left = wma.filter.mask(pd, mask_left, preserve_point_data=True, preserve_cell_data=True, verbose=False)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/whitematteranalysis/filter.py", line 434, in mask
    point = inpoints.GetPoint(ptids.GetId(pidx))
KeyboardInterrupt

### when running as an lsf file, I got the following error:

Lmod has detected the following error: The following module(s) are unknown:
"matlab-2011b"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "matlab-2011b"

Also make sure that all modulefiles written in TCL start with the string
#%Module

**Comment by zhangfanmark** [comment]
Hi! 

The tensor2 message should be warning, which should not affect outputs. You already have the output, right? If so, I would not worry about that and just let the program run.

The other error should be related to your lsf env setting. I do not think we use matlab in the code at all.

Regards,
Fan

**Comment by kvandeloo-97** [comment]
Hi Fan, thank you, is it normal to have all 800 cluster files in each sub-folder?
________________________________

**Comment by zhangfanmark** [comment]
Can you please send a screenshot of the file structure? All cluster files should be in one folder, but I am not sure which subfolder you were referring to. thanks.

Regards,
Fam

**Comment by kvandeloo-97** [comment]
So for example, it seems that instead of sorting the cluster_00001.vtp file into either 'tracts_commissural', 'tracts_left_hemisphere' and 'tracts_right_hemisphere', it is putting it in all 3. Not sure if this is normal.

Best,
Katie
________________________________

**Comment by zhangfanmark** [comment]
Yes, that is normal. We are performing bilateral clustering, which will identify streamlines in both hemispheres of the brain. This will improve the robustness of the clustering algorithm to form clusters. Then later here, we separate them because most people are interested in looking at white matter tracts in each hemisphere separately. So if it is a hemispheric cluster, you will find non-empty vtk files in the left and right subfolders. If it is a commissural cluster, you will find a non-empty vtk file in the commissural folder.  

Regards,
Fan

**Comment by kvandeloo-97** [comment]
Ah, wonderful! Thank you again for your quick response.

Kind Regards,
Katie
________________________________

**Comment by zhangfanmark** [comment]
Thank you. this is solved I think.
