### ISSUE TITLE
Possible bug in wm_register_multisubject_faster.py

### ISSUE THREAD

**Issue by drombas** [SlicerDMRI/whitematteranalysis#116]
Hi! Trying to register 2 bundles ([link to data](https://drive.google.com/drive/folders/158PfRUVbCq_Ij_4yoFVGBkFtvKUr6u9t?usp=sharing)) I encountered an error.

**Used command:**
`wm_register_multisubject_faster.py input output`

**Obtained error:**
<img src="https://user-images.githubusercontent.com/50577357/155839868-5041737c-e048-42a4-9fe7-c74d4f5972db.png" width="800" height="800">
**Possible solution**
I believe the problem is that `fibers_per_subject` [here](https://github.com/SlicerDMRI/whitematteranalysis/blob/ac63f006f212a7bf42c5eb4518379af2fe13494b/whitematteranalysis/congeal_multisubject.py#L203) changes to a float when divided by 1 and fails when used as index. 
This happens when `len(self.polydatas) - 1 = 1` (it might be an edge case or something wrong with my data).
Casting `fibers_per_subject` to int could be a simple fix.

Thanks!

**Comment by ljod** [comment]
Thank you we for the bug report and suggestion! We believe this should be fixed now.

**Comment by drombas** [comment]
Yes, thanks!
