### ISSUE TITLE
Questions about .csv files

### ISSUE THREAD

**Issue by Joshuazzzzs** [SlicerDMRI/whitematteranalysis#121]
Hi! 
The row names in the first column of the final.CSV file represent exactly which part of the brain's fiber bundle? I don't know what these abbreviations mean. For example, what does "T_AF_Left" mean?

**Comment by jhlegarreta** [comment]
@Joshuazzzzs "T_AF_left" means left arcuate fasciculus. The complete list of bundles are in Table 3 in [https://doi.org/10.1016/j.neuroimage.2018.06.027](https://doi.org/10.1016/j.neuroimage.2018.06.027).

They are also found in this ORG-Atlas repository documentation:
https://github.com/SlicerDMRI/ORG-Atlases/blob/master/Tracts-in-ORG-800FC-100HCP.md

Which, in turn, is referenced in the SlicerDMRI documentation website: 
https://github.com/SlicerDMRI/slicerdmri.github.io/blob/master/atlas/index.md

Rendered in:
http://dmri.slicer.org/atlases/

Hope this helps.

@pieper @ljod @zhangfanmark I think the issue can be considered as answered and thus be closed.

**Comment by pieper** [comment]
Thanks for answering @jhlegarreta 👍
