### ISSUE TITLE
missing atlas.csv and json files

### ISSUE THREAD

**Issue by JoshuaKening** [SlicerDMRI/whitematteranalysis#216]
I recently installed the 'whitematteranalysis' package using the command pip install git+https://github.com/SlicerDMRI/whitematteranalysis.git. However, after installation, I noticed that the data/atlas directory in the whitematteranalysis folder inside Anaconda3's site-packages does not contain the different versions of atlas.csv and the related JSON files. These files were available in previous versions.
<img width="1113" alt="image" src="https://github.com/SlicerDMRI/whitematteranalysis/assets/129246293/10babc73-e32c-4157-896e-c42840b2d83d">

**Comment by jhlegarreta** [comment]
PR #220 should fix this. Try doing
```
pip install git+https://github.com/SlicerDMRI/whitematteranalysis.git@7f0ab2fc5d33c8b3ac83faf164de2de37dbd53b4
```

**Comment by JoshuaKening** [comment]
> PR #220 should fix this. Try doing
> 
> ```
> pip install git+https://github.com/SlicerDMRI/whitematteranalysis.git@7f0ab2fc5d33c8b3ac83faf164de2de37dbd53b4
> ```

It works! Thank you.
