### ISSUE TITLE
Availability of predefined hierarchy?

### ISSUE THREAD

**Issue by wasserth** [SlicerDMRI/whitematteranalysis#60]
I am trying to automatically extract major fiber bundles (e.g. CST) from my tractograms using the method described in "Automated white matter fiber tract identification in patients with brain tumors". I ran the code in this repository and it worked really well (Thanks for the clear documentation!).
But now I have 800 clusters and have to assign them to anatomical tracts like CST, SLF, AF... In the paper a hierarchy was created by experts for that purpose. Is that hierarchy available?

**Comment by ljod** [comment]
Hi we are happy that you were able to use the code easily!

Please contact me directly so we can arrange to share the cluster atlas and hierarchy from our recent paper. odonnell at bwh dot harvard dot edu

**Comment by ljod** [comment]
Closing due to recent atlas release.
