### ISSUE TITLE
wm_harden_transform: different numbers of inputs and outputs error

### ISSUE THREAD

**Issue by anastasia-nik** [SlicerDMRI/whitematteranalysis#97]
Getting error when running wm_harden_transform.py script:
The numbers of inputs and outputs are different. Check log file for error.

How can I fix it? Thank you in advance!

![Error](https://user-images.githubusercontent.com/70979050/92530616-6468ce00-f235-11ea-8f33-3b85e839a3c7.jpg)

**Comment by zhangfanmark** [comment]
Hi @anastasia-nik can you check what the log file says? it should be in transform output folder.

**Comment by anastasia-nik** [comment]
Log file in ./FiberClustering/TransformedClusters/...._Whole_Brain/ says "sh: 1: /home/nora/Slicer-4.10.2-linux-amd64: Permission denied"

**Comment by zhangfanmark** [comment]
the parameter for the path of Slicer should be Slicer binary file, not the folder. On Linux, the binary file should be under the folder you have here.

**Comment by anastasia-nik** [comment]
I'm new at all of this and I've been trying to fix this mistake for a long time and, finally, with your help I DID IT. Thanks a lot!

**Comment by zhangfanmark** [comment]
You are welcome : ) Please let us know if there is anything else we can help. I will close this issue now.
